server:
  port: 8010
spring:
  application:
    name: main-service
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
#management:
#  security:
#    enabled: false