server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  #overwrite default sensitive headers settings, by set only this headers as sensitive, so other headers such as Authorization can trasform normally.
  sensitive-headers: Cookie,Set-Cookie
  ignoredServices: '*'
  routes:
    main-service:
      path: /**
    hystrix-dashboard:
      path: /hystrix/**
      stripPrefix: false
    hystrix-dashboard-webjars:
      path: /webjars/d3js/**
      serviceId: hystrix-dashboard
      stripPrefix: false
    hystrix-dashboard-proxystream:
      path: /proxy.stream
      serviceId: hystrix-dashboard
      stripPrefix: false
    service-one:
      path: /getTime
      
